"""Parametry fuzji heurystyk AI-video.

Cel: ograniczyć konflikty przy kolejnych PR-ach. Strojenie progów odbywa się tutaj,
bez ciągłego edytowania `evaluate.py`.
"""

LOW_TEXTURE_THRESHOLD = 1
HF_RATIO_THRESHOLD = 0.50
MAX_AREA_RATIO_THRESHOLD = 0.18
LOWER_THIRD_HARD_THRESHOLD = 0.60
POINTS_THRESHOLD_DEFAULT = 5
HIGH_SCORE_OVERRIDE_THRESHOLD = 6
POINTS_THRESHOLD_SWEEP = [3, 4, 5]
HF_RATIO_THRESHOLD_SWEEP = [0.45, 0.50, 0.55, 0.60, 0.65, 0.70]
LOW_TEXTURE_THRESHOLD_SWEEP = [1, 2, 3]

# Broadcast trap heuristics
LOWER_THIRD_HARD_UPPER_MAX = 0.20
SCOREBOARD_HF_MIN = 0.65
BILLBOARD_CENTER_RATIO_MIN = 0.55
BILLBOARD_GLOBAL_MOTION_MIN = 10.0
BILLBOARD_TEXTURE_MIN = 1200.0
CLEAN_AI_HF_THRESHOLD = 0.50
CLEAN_AI_HF_THRESHOLD_SWEEP = [0.42, 0.45, 0.48, 0.50, 0.53, 0.56]
CLEAN_AI_MAX_AREA_RATIO = 0.02
CLEAN_AI_MAX_AREA_RATIO_SWEEP = [0.01, 0.02, 0.03, 0.05]
# Uwaga: te sweepy są zdefiniowane, ale run_threshold_sweep() nie iteruje ich
# bezpośrednio. Pozostawiono je jako dokumentację przestrzeni do dalszego strojenia.
ENABLE_CLEAN_AI_RESCUE = True

# Soft broadcast guard (fallback when hard traps do not fire)
ENABLE_BROADCAST_SOFT_GUARD = True
BROADCAST_SOFT_SCOREBOARD_LOWER_RATIO_MIN = 0.35
BROADCAST_SOFT_SCOREBOARD_UPPER_RATIO_MIN = 0.40
BROADCAST_SOFT_SCOREBOARD_CENTER_RATIO_MAX = 0.25
BROADCAST_SOFT_SCOREBOARD_OF_COUNT_MIN = 10
BROADCAST_SOFT_BILLBOARD_TEXTURE_VAR_MIN = 18.0
BROADCAST_SOFT_BILLBOARD_UPPER_RATIO_MAX = 0.35
BROADCAST_SOFT_BILLBOARD_OF_COUNT_MIN = 8
BROADCAST_SOFT_LOWERTHIRD_RATIO_MIN = 0.55

# Position-agnostic OF recovery for cropped AI videos
ENABLE_CROPPED_OF_RECOVERY = True
CROPPED_OF_RECOVERY_BONUS_POINTS = 2
CROPPED_OF_RECOVERY_MIN_OF_COUNT = 3
CROPPED_OF_RECOVERY_MAX_AREA_RATIO = 0.02
CROPPED_OF_RECOVERY_MAX_LOWER_RATIO = 0.30
CROPPED_OF_RECOVERY_MAX_CENTER_RATIO = 0.35
CROPPED_OF_RECOVERY_MIN_LOW_TEXTURE_SHARE = 0.66

# Evaluate-level thresholds
AI_STYLE_CLIP_HIGH_CONF_THRESHOLD = 0.60
AI_STYLE_SOFT_OVERRIDE_SCORE = 4.0
LOWER_THIRD_QUALITY_PROB_THRESHOLD = 0.50

# Temporal Consistency (S1) — TC Conditional Boost
TC_MIN_AI_STYLE_PROB = 0.44
TC_ELIGIBLE_SCORES = [2, 3]
TC_MAX_LOWER_THIRD_PROB = 0.50  # guard against fp_trap FP
